### ISSUE TITLE
Invalid 'main' field in package.json

### ISSUE THREAD

**Issue by smucode** [Noriller/easy-filter#13]
Invalid 'main' field in package.json. Points to `dist/index.js` which doesn't exist.

Things work, just get a warning when using the lib with remix.run on node 18.

Great work btw, it's just what i needed for some clientside filtering 👍

**Comment by Noriller** [comment]
Thank you for bringing this up. =D

It should be a simple fix, so hopefully between today and tomorrow I'll push a fix.
