### ISSUE TITLE
Possible to configure how multiple tokens are treated

### ISSUE THREAD

**Issue by smucode** [Noriller/easy-filter#15]
I'd like to refine the search by typing several words which matches different fields of the input. 

In the given example, the user first types `bar` to get a list of all users matching that tag. Then refines the search typing `jo`. I'd like in my usecase only the first record to match the query.

```
const EasyFilter = require('@noriller/easy-filter')

const array = [
	{ _id: 1, name: "John", age: 42, tags: ["Foo", "Bar"] },
	{ _id: 2, name: "Jane", age: 69, tags: ["Bar", "Baz", "123"] }
]

const filter = EasyFilter.default(array)
const result = filter.search('bar jo')

// returns both records, expected it to only return the first
```

**Comment by smucode** [comment]
Wrapping the input in quotes does exactly what i'd like :)

```
const EasyFilter = require('@noriller/easy-filter')

const array = [
	{ _id: 1, name: "John", age: 42, tags: ["Foo", "Bar"] },
	{ _id: 2, name: "Jane", age: 69, tags: ["Bar", "Baz", "123"] }
]

const filter = EasyFilter.default(array)
const result = filter.search('"bar jo"')
```

**Comment by smucode** [comment]
Well, it seems like blindly wrapping the input in double quotes doesn't do what i'd expect after all. It solves the example above. But wrapping `tags:3` in double quotes returns nothing.

```
const EasyFilter = require('@noriller/easy-filter')

const array = [
	{ _id: 1, name: "John", age: 42, tags: ["Foo", "Bar"] },
	{ _id: 2, name: "Jane", age: 69, tags: ["Bar", "Baz", "123"] }
]

const filter = EasyFilter.default(array)
const result = filter.search('"tags:3"')
```

Is there a way to solve this without me having any knowledge about the query. Eg. I can try to detect from how and what the user inputs, if i should wrap it in quotes or not. But it would be awesome if there was a way to handle this with an option or something.

**Comment by Noriller** [comment]
This one seems like a bug
```js
const _result = filter.search('" tags:3"');
const result_ = filter.search('"tags:3 "');
```
Adding a space solves it.

In the use case that I used to create this, I generated and appended to the query what I needed based on set parameters for each case. I also exposed some of the options so power users could take advantage of that.
